export interface NewsItem {
    id: number;
    title: string;
    date: string;
    excerpt: string;
    category: string;
    link: string;
    image?: string;
}

export const fetchFacebookPosts = async (): Promise<NewsItem[]> => {
    try {
        // Fetch from the static JSON file generated by GitHub Actions (or local script)
        // This removes the need for the API token in the frontend code.
        const response = await fetch(`${import.meta.env.BASE_URL}news.json`);

        if (!response.ok) {
            throw new Error(`Error fetching news: ${response.statusText}`);
        }

        const data: NewsItem[] = await response.json();
        return data;
    } catch (error) {
        console.error('Failed to fetch news feed:', error);
        return [];
    }
};
